services:
  - type: web
    name: ecoplate-ai-backend
    env: python

    rootDir: ecoplate-backend/ecoplate-backend

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0